### PR TITLE
Modify and rename setup.py (Fixes #36)

### LINKED ISSUE #36: Remove PyBadger library from PyPI
This lib does not belong on PyPI. This requires the following:

- [ ] `setup.py`must be renamed to `setup.py.disabled` and the contents replaced with the code block at the bottom of this issue.

- [ ] Library must be manually removed from PyPI. (I can do this once `setup.py` is taken care of.)

`setup.py.disabled` contents:
```
"""
This library is not deployed to PyPI. It is either a board-specific helper library, or
does not make sense for use on or is incompatible with single board computers and Linux.
"""
```

### PR DESCRIPTION
**Pull request by SAK917**
Hi @kattni, I saw this issue was languishing in the Good First Issue list and thought I would take a stab at it.  I replaced the contents of `setup.py` with the comment block you provided in the issue and then renamed the file to `setup.py.disabled` as instructed.  Let me know if there is anything else I need to do...

### CODE REVIEW

**Comment by SAK917** [comment]
It looks like the check is failing in Pylint with the "similar lines in 2 files" error.  I believe I saw on Discord that you were looking into this error, so I won't pursue it until I hear otherwise.

**Comment by kattni** [comment]
@SAK917 Your changes are perfect! As for the Pylint failure - how comfortable are you with Git and GitHub? I can walk you through the changes that need to be made to get this PR passing. We have a library patch in the works, but it may be a week or so before it's deployed. Let me know if you'd like to give it a try!

**Comment by SAK917** [comment]
Hi @kattni, I am ok with Git / GitHub and wanting to learn more so just let me know what I can do and I am happy to do it.

**Comment by kattni** [comment]
@SAK917 Ok, so what you'll do is make changes in the same branch as used for this PR (which is `master` on your fork) and `git push` the same as you did with this change. It will automatically update this PR with your new changes. If you run into issues with this, please ping me and I will help you sort it out.

Please update the following two files. 

First `Adafruit_CircuitPython_PyBadger/.github/workflows/build.yml` should look like the contents of [this gist](https://gist.github.com/kattni/a34ca2c7fcb3abd5f9cb7ff3b9703f31).

Second `Adafruit_CircuitPython_PyBadger/.pre-commit-config.yaml` should look like the contents of [this gist](https://gist.github.com/kattni/5a327019680c99d764b39625587e8c1d).

**Comment by kattni** [comment]
@SAK917 You did everything right. I need to look at this failure as soon as this meeting is over, and likely will merge your changes and we'll deal with it in an issue.

**Review by kattni — APPROVED** [review]
@SAK917 Thank you again for doing this! I'm going to merge it and file an issue regarding the failure, as it is an issue with the library itself.

**Comment by SAK917** [comment]
Happy to help @kattni, and don't hesitate to let me know if there is anything else I can do.  I know you folks are super busy with the RP2040 releases about to hit and I felt conflicted about dredging up an old issue, but also thought that getting some old issues off the books is always a good thing as well.  If you want me to pause looking at these older "Good First Issues" just let me know.

**Comment by kattni** [comment]
@SAK917 We're always happy to see older issues getting taken care of. If you would like to start picking up some more issues, please feel free! I would love to see that. To clarify, we are never so hyperfocused on any one thing that we expect development to pause elsewhere. Sometimes it means taking extra time to get to reviewing a PR, but we have never considered suggesting that folx stop submitting them. We have a team for a reason - in the event that something big like the RP2040 happens, we can still keep everything else flowing. 

If you pick anything else up, please comment on the issue that you're working on it. When you create the PR, you can tag me directly so I can request a review from our team (since I don't think you can request reviews... if you can, request from CircuitPythonLibrarians!).

**Comment by SAK917** [comment]
@kattni  Thanks for the response and I do have one more contribution question: I noticed there seem to be a lot of similar library infrastructure issues.  If there is something repetitive or not too in-depth that I can stop and pick back up frequently due to interruptions, I am happy to take a stab at it.  I have time to work on that kind of mind numbing stuff right now, and it would mesh with my currently funky schedule.  There are a lot of things listed under Library Infrastructure Issues and I don’t know where best to start (or if it is even a priority), but if you want to take me up on this just point me in the direction of what you need done!

**Comment by kattni** [comment]
@SAK917 I took a look, and nearly all of those issues require permissions or access that you wouldn't have. The only one you could consider looking into is `Example file(s) missing sensor/library name`. A couple of those are a more complicated decision, but a few of them are simple. The problem here is that if there is an Adafruit Learn guide that uses the code, **the guide must be updated**, and again, that's something you wouldn't be able to do. I think for now, don't worry about the infrastructure issues.

**Pull request merged**
