### PR TITLE
Update the pixel_shader usage of OnDiskBitmap

### PR DESCRIPTION
**Pull request by lesamouraipourpre**
OnDiskBitmap has had incompatible changes in `7.0.0-alpha.3` - Ref: https://github.com/adafruit/circuitpython/pull/4823
This PR is part of a group of updates for this change - https://github.com/adafruit/circuitpython/issues/4982

This PR updates the library to the combined usage for CP6 & CP7.

Also:
Refactor code referencing CircuitPython 4 & 5
Filled out requirements.txt
Include most of the packages in api.rst.
*I can't get docs to build for cpb_gizmo so have left it out of the docs for now.*

It has not been tested as I do not have the hardware. *I tried testing with the PyPortal example but I am getting this bug (even before changes):* https://github.com/adafruit/circuitpython/issues/4985

### CODE REVIEW

**Review by jepler — APPROVED** [review]
This seems fine, but I don't know why CI/actions has been having trouble with it.  No testing performed.

**Comment by lesamouraipourpre** [comment]
I've tried pulling this PR into a clean directory and `pip install -r requirements.txt` is behaving like there is a clashing dependency graph. When it finishes locally, I'll try to figure out what the trigger dependency is.

**Comment by lesamouraipourpre** [comment]
The problem is `adafruit-circuitpython-gizmo`. There are requirements changes in it that have been merged but not released - https://github.com/adafruit/Adafruit_CircuitPython_Gizmo/compare/1.3.2...HEAD
I had the HEAD installed with `pip install -e .` instead of the PyPi version.

**Review by FoamyGuy — APPROVED** [review]
I think the necessary changes in the Gizmo library have been released by now. I re-ran the actions and it is now passing.

These changes look good to me. I tested the simpletest script successfully on a PyGamer with `7.0.0-alpha.4`

Thanks for these updates @lesamouraipourpre and for taking care of the old v4 / 5 fallback displayio code.

**Pull request merged**
