### PR TITLE
Remove gamepad usage

### PR DESCRIPTION
**Pull request by FoamyGuy**
ref: [#4940](https://github.com/adafruit/circuitpython/pull/4940)

This removes all usages of `gamepad` and `gamepadshift` and replaces them with the analogous APIs from `keypad`

I tested these changes on all affected devices supported by this library: PyBadge, PyGamer, CLUE, CPB+Gizmo, and PewPewM4 all on CircuitPython 7.0.0-alpha.5

### CODE REVIEW

**Comment by dhalbert** [comment]
@kattni and I discussed a plan for this yesterday. If we substitute `keypad` for `gamepad` and `gamepadshift` right now, then it will break for users using CircuitPython 6.3.0. Instead, we can leave `gamepad` in for 7.0.0, but deprecate it. Once 7.0.0 is final, we will drop 6.3.0 support and can change the library. So this PR can just be held in abeyance until then.

The other possibility is to add conditional import code that allows either `gamepad`/`gamepadshift` or `keypad` to be used. If `keypad` is not present, then the library reverts to the old code. When 6.x is no longer supported, this code can be removed.

@FoamyGuy How does this sound to you?

**Comment by FoamyGuy** [comment]
Waiting until 7.0.0 is final sounds good to me. 

I think making the code conditional and supporting both would end up being a bit overly complex due to the differing APIs between them.

**Comment by kattni** [comment]
Converting this PR to draft status so it's clear we're waiting to merge it. Once 7.0.0 is released, we can revisit. Thanks!

**Comment by dhalbert** [comment]
We can proceed with this, right? See #52 for a user caught by this.

**Comment by kattni** [comment]
@FoamyGuy Can you please drop an empty commit in here so the checks run again? It's almost certainly out of date at this point. Once passing we can get this merged.

**Comment by FoamyGuy** [comment]
@kattni empty commit added. Will check back in a bit to see if anything needs tweaked to get it passing.

**Review by kattni — APPROVED** [review]
Looks like it's passing! Thanks!

**Pull request merged**
